name: Docker Image CI

env:
  DOCKER_ORG: actions

on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - reopened 
      - synchronize
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "./*.md"
      - "./**/*.md"
      - .gitignore
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ci_index: [1]
        ci_total: [1]

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: |
        RAW_VERSION=${GITHUB_REF/refs\/tags\//}
        VERSION=${RAW_VERSION#${GITHUB_REF}}
        echo ::set-output name=VERSION::${VERSION:-latest}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker Buildx (build)
      env:
        MAX_WORKERS: ${{ matrix.ci_total }}
        WORKER: ${{ matrix.ci_index }}
      run: |
        docker buildx create --use
        echo "FROM scratch" | docker buildx build -
        .github/build.sh ${DOCKER_ORG} ${{ steps.get_version.outputs.VERSION }}
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    - name: Docker Buildx (push)
      env:
        MAX_WORKERS: ${{ matrix.ci_total }}
        WORKER: ${{ matrix.ci_index }}
      run: |
        .github/deploy.sh ${DOCKER_ORG} ${{ steps.get_version.outputs.VERSION }}
